bloom-filter:
  expected-insertions: 100000
  false-positive-probability: 0.0001
  enable-logging: true
  recovery: false


logging:
  level:
    root: info
    io.github.dalowed: debug
  file:
    name: bitmap/bloomLog.txt
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"